# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|  
  #
  # Eric:Define a single virtual machine with 2G memory and 2 cpus
  #
  config.vm.box = "centos/7"
  config.vm.define "signle-host"
  config.vm.hostname = "signle-host"
  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
  end
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "2048"]
    v.customize ["modifyvm", :id, "--cpus", '2']
  end

  #
  # Eric: install Docker-ce
  #
  config.vm.provision "file", source: "./Dockerfile", destination: "Dockerfile"
  config.vm.provision "file", source: "./hello", destination: "hello"
  config.vm.provision "shell", inline: <<-SHELL
    # install docker
    curl -fsSL get.docker.com -o get-docker.sh
    sh get-docker.sh

    # start docker service
    sudo groupadd docker
    sudo usermod -aG docker vagrant
    sudo systemctl start docker

    rm -rf get-docker.sh
  SHELL
end
